### ISSUE TITLE
celeba_hq.ckpt .etc pretrain model  

### ISSUE THREAD

**Issue by Gavin-Evans** [gwang-kim/DiffusionCLIP#27]
hi, 
I got an error when running.

Downloading: "https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt" to C:\Users\xx/.cache\torch\hub\checkpoints\celeba_hq.ckpt
ERROR - main.py - 2023-04-22 20:48:44,842 - Traceback (most recent call last):
  File "main.py", line 212, in main
    runner.clip_finetune()
  File "E:\DL\generation\diffusionCLIP\DiffClip\diffusionclip.py", line 82, in clip_finetune
    init_ckpt = torch.hub.load_state_dict_from_url(url, map_location=self.device)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\site-packages\torch\hub.py", line 731, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\site-packages\torch\hub.py", line 597, in download_url_to_file
    u = urlopen(req)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "D:\ProgramData\anaconda3\envs\diffusionclip\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

pretrain models aren't automatically downloaded in the code,  may you share them in Google Drive? 

thanks.

**Comment by nihaomiao** [comment]
same issue...

**Comment by pochenyun72** [comment]
I think that's because this project references the code from [SDEdit](https://github.com/ermongroup/SDEdit)，its pretrained checkpoints can't download too!

**Comment by JamesSand** [comment]
hi, has anybody solved this problem? I have also encountered this problem.

**Comment by zhangyongliang666** [comment]
"Where can I download the pre-trained model for Dog Face 256*256? The previously provided download link is no longer valid. Could someone please share an updated link?"

**Comment by Honeybadger-LSX** [comment]
邮件已收到，会尽快回复，祝安！

**Comment by zhangyongliang666** [comment]
Hello, I've observed that the afhqdog_p2.pt file mentioned earlier is expected to be used for 3-class classification. However, when incorporated into the code, it indicates a 307-class classification. Upon investigation, I noticed that all the weight files shared in the Google Drive link have the same file size. Could there be an issue with these weight files?
