### ISSUE TITLE
Error due to unable to download .ckpt files 

### ISSUE THREAD

**Issue by maheshreddy24** [gwang-kim/DiffusionCLIP#44]
Hey I'm unable to run the model this error encounters 
./runs/test_ED_CelebA_HQ_t500_ninv40_ngen6_neanderthal
Downloading: "https://image-editing-test-12345.s3-us-west-2.amazonaws.com/checkpoints/celeba_hq.ckpt" to /home2/rohitb/.cache/torch/hub/checkpoints/celeba_hq.ckpt
ERROR - main.py - 2024-11-26 20:48:09,065 - Traceback (most recent call last):
  File "main.py", line 217, in main
    runner.edit_images_from_dataset()
  File "/home2/rohitb/DiffusionCLIP/diffusionclip.py", line 760, in edit_images_from_dataset
    ckpt = torch.hub.load_state_dict_from_url(url, map_location=self.device)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/site-packages/torch/hub.py", line 555, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/site-packages/torch/hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home2/rohitb/miniconda3/envs/diffusionclip/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by LowerExpectation** [comment]
I have the same error...

**Comment by alexmehta** [comment]
Unclear if this works but I found this: https://huggingface.co/gwang-kim/DiffusionCLIP-CelebA_HQ/blob/main/celeba_hq.ckpt

doesn't seem to have any finetuning applied though.
